version: '3'
services:
  api:
    build: 
      context: ./backend
      target: local-environment
    restart: always
    deploy:
      resources:
        limits:            
          cpus: '0.50'
          memory: 2048M
        reservations:      
          memory: 1042M
    ports:
      - "8080:8080"
    expose:
      - 8080
    depends_on:
      - db
  db:
    image: postgres:alpine
    restart: always
    deploy:
      resources:
        limits:
          cpus: '0.50'
          memory: 2048M
        reservations:
          memory: 1042M
    environment:
      POSTGRES_USER: api_spring
      POSTGRES_PASSWORD: spring
      POSTGRES_DB: api_spring
    ports:
      - "5432:5432"
    expose:
      - 5432
    volumes:
      - ./postgres/init.sql:/docker-entrypoint-initdb.d/init.sql
      - ./postgres/data:/var/lib/postgresql/data